/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_leds_off_after_create(void);
extern void test_turn_on_led(void);
extern void test_turn_off_led(void);
extern void test_turn_on_multiple_leds(void);
extern void test_turn_on_all_leds(void);
extern void test_turn_off_multiple_leds(void);
extern void test_led_state_is_readable(void);
extern void test_out_of_bound_turn_on_no_harm(void);
extern void test_out_of_bound_turn_off_no_harm(void);
extern void test_out_of_bound_produce_runtime_error(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("test_LedDriver.c");
  RUN_TEST(test_leds_off_after_create, 16);
  RUN_TEST(test_turn_on_led, 23);
  RUN_TEST(test_turn_off_led, 29);
  RUN_TEST(test_turn_on_multiple_leds, 36);
  RUN_TEST(test_turn_on_all_leds, 43);
  RUN_TEST(test_turn_off_multiple_leds, 49);
  RUN_TEST(test_led_state_is_readable, 56);
  RUN_TEST(test_out_of_bound_turn_on_no_harm, 63);
  RUN_TEST(test_out_of_bound_turn_off_no_harm, 71);
  RUN_TEST(test_out_of_bound_produce_runtime_error, 80);

  return (UnityEnd());
}
